# Redirect all HTTP requests to HTTPS
server {
  listen 80;
  server_name sabinechat.com www.sabinechat.com;

  return 301 https://$host$request_uri;
}

# HTTPS Server block
server {
  listen 443 ssl;
  server_name sabinechat.com www.sabinechat.com;

  ssl_certificate /etc/nginx/certs/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/privkey.pem;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri /index.html;
  }

  location /api/ {
    proxy_pass http://server:5000;  # The name of your Flask container in docker-compose
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}
